image: rocker/rstudio
test:
   script:
   - R -e 'install.packages(c("testthat", "Rcpp", "stats", "BiocManager","lme4"))'
   - R -e 'BiocManager::install("Biobase","BiocParallel")'
   - R CMD build . --no-build-vignettes --no-manual
   - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
   - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
